import jsPDF from 'jspdf'
import autoTable from 'jspdf-autotable'
import type { Inspection, Site, Asset } from '../types'
import { formatGPS, formatTimestamp } from './gps'

export function generateInspectionPDF(
  inspection: Inspection,
  site?: Site,
  asset?: Asset
): void {
  const doc = new jsPDF()
  const pageWidth = doc.internal.pageSize.getWidth()

  doc.setFillColor(15, 118, 110)
  doc.rect(0, 0, pageWidth, 30, 'F')
  doc.setTextColor(255, 255, 255)
  doc.setFontSize(18)
  doc.text('InspectField', 14, 14)
  doc.setFontSize(10)
  doc.text('Inspection Report', 14, 22)

  doc.setTextColor(0, 0, 0)
  doc.setFontSize(16)
  doc.text(inspection.title, 14, 42)

  doc.setFontSize(10)
  doc.setTextColor(100, 100, 100)
  let y = 52
  if (site) {
    doc.text(`Site: ${site.name}`, 14, y)
    y += 6
  }
  if (asset) {
    doc.text(`Asset: ${asset.name}`, 14, y)
    y += 6
  }
  doc.text(`Status: ${inspection.status.replace('_', ' ').toUpperCase()}`, 14, y)
  y += 6
  doc.text(`Due: ${formatTimestamp(inspection.dueDate)}`, 14, y)
  y += 6
  if (inspection.completedAt) {
    doc.text(`Completed: ${formatTimestamp(inspection.completedAt)}`, 14, y)
    y += 6
  }
  if (inspection.gps) {
    doc.text(`GPS: ${formatGPS(inspection.gps)}`, 14, y)
    y += 6
  }

  const tableData = inspection.items.map((item, i) => [
    String(i + 1),
    item.label,
    item.category || '-',
    item.status.toUpperCase(),
    item.notes || '-',
  ])

  autoTable(doc, {
    startY: y + 4,
    head: [['#', 'Item', 'Category', 'Status', 'Notes']],
    body: tableData,
    styles: { fontSize: 8 },
    headStyles: { fillColor: [15, 118, 110] },
    didParseCell: (data) => {
      if (data.column.index === 3 && data.section === 'body') {
        const status = data.cell.raw as string
        if (status === 'FAIL') data.cell.styles.textColor = [220, 38, 38]
        if (status === 'PASS') data.cell.styles.textColor = [22, 163, 74]
      }
    },
  })

  const finalY = (doc as unknown as { lastAutoTable: { finalY: number } }).lastAutoTable.finalY

  if (inspection.signature) {
    doc.setFontSize(12)
    doc.setTextColor(0, 0, 0)
    doc.text('Digital Signature', 14, finalY + 14)
    doc.addImage(inspection.signature.dataUrl, 'PNG', 14, finalY + 18, 60, 30)
    doc.setFontSize(9)
    doc.setTextColor(100, 100, 100)
    doc.text(
      `Signed by: ${inspection.signature.signerName}${inspection.signature.signerRole ? ` (${inspection.signature.signerRole})` : ''}`,
      14,
      finalY + 54
    )
    doc.text(`Date: ${formatTimestamp(inspection.signature.timestamp)}`, 14, finalY + 60)
  }

  const photoItems = inspection.items.filter(item => item.photos.length > 0)
  if (photoItems.length > 0) {
    let photoY = (inspection.signature ? finalY + 70 : finalY + 14)
    doc.setFontSize(12)
    doc.setTextColor(0, 0, 0)
    doc.text('Photo Evidence', 14, photoY)
    photoY += 8

    for (const item of photoItems) {
      for (const photo of item.photos) {
        if (photoY > 240) {
          doc.addPage()
          photoY = 20
        }
        try {
          doc.addImage(photo.dataUrl, 'JPEG', 14, photoY, 80, 60)
          doc.setFontSize(8)
          doc.setTextColor(100, 100, 100)
          doc.text(`${item.label}${photo.caption ? ` - ${photo.caption}` : ''}`, 14, photoY + 66)
          photoY += 74
        } catch {
          // skip invalid images
        }
      }
    }
  }

  doc.setFontSize(8)
  doc.setTextColor(150, 150, 150)
  doc.text(`Generated by InspectField on ${formatTimestamp(new Date().toISOString())}`, 14, 285)

  doc.save(`inspection-${inspection.id}.pdf`)
}
